### ISSUE TITLE
Generation of slm files for simulation

### ISSUE THREAD

**Issue by mohamedghamad** [pulp-platform/bigpulp#10]
Hello,

Going through sim-bigpulp-z-70xx, I have been struggling to get the simulation to work with any meaningful application. At this point, I could get Vivado to finish compilation and fire up QuestaSim; which in return, waits for me to 'run -all'.

Now regarding the missing .slm files, I am not sure if I have those generated correctly. I did use pulp-sdk while targeting bigpulp-z-7045 and I tried to compile several pulp-rt-examples; however, none of them seem to have generated the correct .slm files.

So my first question is, what is the correct way to generate the slm_files while working with sim-bigpulp-z-70xx?

My second question is how come this repository's test benches do not match anything in the pulp-rt-examples by name? I believe this is the source of my confusion as I can't relate these TBs to any of the pulp-rt-examples which are compiled by the SDK. My approach was to compile pulp-rt-examples/hello and try the generated slm files with all of the available TBs one at a time.

In PULPino, each application has its own TB, its C file to be compiled and its own slm files.

Things I thought to consider,
1- Fill missing slm files with zeros
2- Fill missing slm files with NOP instruction from RISC-V manual
3- Use some other config with pulp-sdk, not sure what could be the difference across other bigPULP configs or even the hero-z-7045 config.

I would be glad if I could get pulp-rt-examples/periph/uart/send to work in sim-bigpulp-z-70xx.

Hoping you can help me with that,
Thank you

**Comment by andreaskurth** [comment]
Regarding .slm file generation: What Makefile are you using? If you include `$(PULP_SDK_INSTALL)/rules/pulp_rt.mk` and initialize with `make conf` then build with `make all`, you should get .slm files.

Regarding the TB question: The TBs of bigPULP are independent from the RT examples in the SDK because bigPULP has a more complex memory interface and different peripherals than other PULP variants, so the focus of its TBs is on that. You should be able to run most of the RT examples with the simple [standalone TB](https://github.com/pulp-platform/bigpulp/tree/standalone-tb/fpga/sim-bigpulp-z-70xx/tb/standalone).

**Comment by mohamedghamad** [comment]
Hi Andreas,

The thing is that the standalone TB looks for the following slm_files:
l2_ram_cut0_lo.slm
l2_ram_cut0_hi.slm
tcdm_bank<0 to 15>.slm

When I run any of the Makefiles in pulp-rt-examples (say pulp-rt-examples/time/timer_periodic or pulp-rt-examples/hello) I end up with flash_stim.slm only.

Shouldn't more slm files be generated along with flash_stim.slm or should I somehow map it to the 18 files the TB is looking for? Is there something wrong with my configs?

If it helps, these are my current configs:
PULP_CURRENT_CONFIG 		= "bigpulp-z-7045@config_file=chips/bigpulp-z-7045/bigpulp-z-7045.json"
PULP_CURRENT_CONFIG_ARGS	= "platform=rtl"

**Comment by andreaskurth** [comment]
Yes, those SLM files should be generated.

Could you please try
`PULP_CURRENT_CONFIG=hero-z-7045@config_file=pulp-sdk/configs/json/hero-z-7045.json`?

`CONFIG_ARGS` should be fine, but you could try to switch to `platform=hsa`, which generates SLM files in addition to a binary for execution on an FPGA (ignore the warnings about failing to connect to the FPGA).

**Comment by mohamedghamad** [comment]
Well, I encountered several errors while using platform HSA. I guess these errors are likely to occur starting from [this](https://github.com/pulp-platform/runner/commit/c12108823cef1a644bc908034ac0c1fb4d76cf98) commit of pulp-platform/runner
In my trials, I downloaded missing files from other revisions/repos and manipulated a lot of Python files to work around the errors.

Finally, all SLM files were generated and I think the simulation works now.
I tried pulp-rt-examples/hello and pulp-rt-examples/uart/send and both simulated for some time with no illegal instruction errors until the intr_eoc signal turned to high.

One last thing is that there was not even a slight change in any of the UART nets even though I expected them to receive the example's printf() output, is this expected?

Edit: I found the expected character output in
testbench/DUT/pulp_soc_i/soc_registers/i_apb_uart/PWDATA

For a reason, it is not passed to the outermost peripheral but I can live with that

**Comment by andreaskurth** [comment]
> Well, I encountered several errors while using platform HSA. I guess these errors are likely to occur starting from this commit of pulp-platform/runner
In my trials, I downloaded missing files from other revisions/repos and manipulated a lot of Python files to work around the errors.

The releases of the PULP SDK that are verified on HERO and thus bigPULP carry the prefix `hero-`. The latest one is [`hero-v1.0.2`](https://github.com/pulp-platform/pulp-sdk/tree/hero-v1.0.2). Sorry, I should have mentioned that earlier. If you need features that are not available in the latest `hero-` PULP SDK release but encounter bugs on bigPULP on later versions of the SDK, please report the issue in the SDK.

> One last thing is that there was not even a slight change in any of the UART nets even though I expected them to receive the example's printf() output, is this expected?

In simulation we usually use an AXI stdout slave that directly prints characters from AXI beats, because that is much faster to simulate than UART. If you want to observe the full UART protocol, you need to ensure that the UART signals are propagated to the TB and that the SDK writes to the UART peripheral instead of the debug stdout slave. The latter seems already to be the case.

**Comment by mohamedghamad** [comment]
Oh, can't believe I haven't noticed that I should not be using the main branch of pulp-sdk.

Thank you very much for your help Andreas.

**Comment by andreaskurth** [comment]
You are welcome. I hope you got the setup you need to work without further issues.

Since the original topic of this issue has been resolved I am closing this issue. Please open a new issue if you encounter different problems.
